server:
  port: 83
spring:
  application:
    name: nacos-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源类型
    driver-class-name: org.gjt.mm.mysql.Driver  #mysql驱动包
    url: jdbc:mysql://localhost:3306/jkgl?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


service-url:
  nacos-user-service: http://nacos-payment-provider
