server:
  port: 80
spring:
  application:
    name: order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源类型
    driver-class-name: org.gjt.mm.mysql.Driver  #mysql驱动包
    url: jdbc:mysql://localhost:3306/jkgl?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
#
#
#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  type-aliases-package: com.jkgl.ek.entities
